/*
 * This file has been auto-generated by CppUTestMock v0.4.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "ExampleModule.h"
}

#include <CppUTestExt/MockSupport.h>

int ExampleModule_f1(int a, int b)
{
    return mock().actualCall("ExampleModule_f1").withIntParameter("a", a).withIntParameter("b", b).returnIntValue();
}

