/*
 * This file has been auto-generated by CppUTestMock v0.4.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "ExamplePeripheral.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& configure_example_peripheral(CppUMockGen::Parameter<int> value);
MockExpectedCall& configure_example_peripheral(unsigned int __numCalls__, CppUMockGen::Parameter<int> value);
}

