/*
 * This file has been auto-generated by CppUTestMock v0.4.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "ExampleModule.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& ExampleModule_f1(CppUMockGen::Parameter<int> a, CppUMockGen::Parameter<int> b, int __return__);
MockExpectedCall& ExampleModule_f1(unsigned int __numCalls__, CppUMockGen::Parameter<int> a, CppUMockGen::Parameter<int> b, int __return__);
}

