/*
 * This file has been auto-generated by CppUTestMock v0.4.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "ExamplePeripheral.h"
}

#include <CppUTestExt/MockSupport.h>

void configure_example_peripheral(int value)
{
    mock().actualCall("configure_example_peripheral").withIntParameter("value", value);
}

